remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Eohan's Portfolio
description: Hi there! I am Eohan, a BS Computer Engineering graduate from the University of the Philippines Diliman with an interest in Data Analysis, Data Science, and Machine Learning. Feel free to look at my projects below :)
